#########################
# DO NOT EDIT THIS FILE #
#########################
from helper.app import Settings
from helper.singleton import Singleton
from helper.game_server import GameServerService
from signalrcore.hub_connection_builder import HubConnectionBuilder

class LHAPIService(metaclass=Singleton):
    def __init__(self):
        self.__game_server = GameServerService()
        self.__hub = None

    def start(self):
        if self.__hub is not None:
            print("lhapi: already started")
            return

        self.__hub = HubConnectionBuilder() \
            .with_url(Settings().lhapi_url + "/teamshub") \
            .with_automatic_reconnect({
                "type": "raw",
                "keep_alive_interval": 10,
                "reconnect_interval": 5,
            }) \
            .build()
        self.__hub.on_open(self.__on_open)
        self.__hub.on_close(self.__on_close)
        self.__hub.on("AssignTeamId", self.__on_assign_team_id)
        self.__hub.on("AssignGameServerUriToGameId", self.__on_assign_game_server_uri_to_game_id)
        self.__hub.start()

    def __on_open(self):
        print("lhapi: connection opened and handshake received")
        self.__hub.send("Register", [Settings().team_id, Settings().game_id])

    def __on_close(self):
        print("lhapi: connection closed")

    def __on_assign_team_id(self, team_id):
        GameServerService().set_team_id(team_id)

    def __on_assign_game_server_uri_to_game_id(self, url):
        Settings().game_server_url = url
        GameServerService().start()
